# Spring Boot 配置
spring:
  application:
    name: bot
  jackson:
    # 驼峰转下划线
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      host: 127.0.0.1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=bot
    username: postgres
    password: 123456

# 服务配置
server:
  port: 8443

# 日志配置
logging:
  file:
    name: ./log/bot.log

# 应用配置
bot:
  app-id: ${BOT_APP_ID}
  app-secret: ${BOT_APP_SECRET}

