# Spring Boot 配置
spring:
  application:
    name: bot
  jackson:
    # 驼峰转下划线
    property-naming-strategy: SNAKE_CASE
    # 忽略空字段
    default-property-inclusion: non_null
    serialization:
      # 忽略空对象
      fail-on-empty-beans: false
    deserialization:
      # 忽略未知字段
      fail-on-unknown-properties: false
  data:
    redis:
      host: 127.0.0.1
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3-max

# 服务配置
server:
  port: 8443

# 日志配置
logging:
  file:
    name: ./log/bot.log

# 应用配置
bot:
  app-id: ${BOT_APP_ID}
  app-secret: ${BOT_APP_SECRET}

